version: '3.8'
services:
    app:
        container_name: e-skincare
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve  --host=0.0.0.0'
        volumes:
        - .:/app
        ports:
        - 8888:8000
        depends_on:
        - database
        - node

    database:
        container_name: e-skincare-database
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 33061:3306

    node:
        container_name: e-skincare-node
        image: node:20-alpine
        volumes:
        - .:/app
        - ./node_modules:/app/node_modules
        working_dir: /app
        command: npm run dev
        ports:
        - 5173:5173

    phpmyadmin:
        container_name: e-skincare-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
        - 8083:80
        depends_on:
        - database

volumes:
    dbdata: